name: experiment_env
channels:
  - conda-forge/label/gcc7
  - r
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - _tflow_select=2.2.0=eigen
  - absl-py=0.4.1=py35_0
  - appdirs=1.4.3=py35h28b3542_0
  - appnope=0.1.0=py35hd172556_0
  - asn1crypto=0.24.0=py35_0
  - astor=0.7.1=py35_0
  - attrs=19.1.0=py_0
  - automat=0.7.0=py35_0
  - backcall=0.1.0=py35_0
  - binutils=1.0.1=0
  - bioconductor-annotate=1.60.0=r351_0
  - bioconductor-annotationdbi=1.44.0=r351_0
  - bioconductor-annotationforge=1.24.0=r351_0
  - bioconductor-biobase=2.42.0=r351h1de35cc_1
  - bioconductor-biocgenerics=0.28.0=r351_1
  - bioconductor-biocinstaller=1.32.1=r351_0
  - bioconductor-biocparallel=1.16.2=r351h12d9a10_1
  - bioconductor-biomart=2.38.0=r351_0
  - bioconductor-biostrings=2.50.2=r351h1de35cc_0
  - bioconductor-bsgenome=1.50.0=r351_0
  - bioconductor-category=2.48.0=r351_0
  - bioconductor-delayedarray=0.8.0=r351h1de35cc_0
  - bioconductor-deseq2=1.22.1=r351h0a44026_0
  - bioconductor-diffbind=2.10.0=r351h0a44026_1
  - bioconductor-edger=3.24.1=r351h0a44026_0
  - bioconductor-genefilter=1.64.0=r351h71abe9c_1
  - bioconductor-geneplotter=1.60.0=r351_0
  - bioconductor-genomeinfodb=1.18.1=r351_0
  - bioconductor-genomeinfodbdata=1.2.0=r351_0
  - bioconductor-genomicalignments=1.18.1=r351h1de35cc_0
  - bioconductor-genomicfeatures=1.34.1=r351_0
  - bioconductor-genomicranges=1.34.0=r351h1de35cc_0
  - bioconductor-go.db=3.7.0=r351_0
  - bioconductor-gostats=2.48.0=r351_0
  - bioconductor-graph=1.60.0=r351h1de35cc_0
  - bioconductor-gseabase=1.44.0=r351_0
  - bioconductor-iranges=2.16.0=r351h1de35cc_0
  - bioconductor-limma=3.38.3=r351h470a237_0
  - bioconductor-rbgl=1.58.1=r351h0a44026_0
  - bioconductor-rgraphviz=2.26.0=r351h0a44026_0
  - bioconductor-roc=1.58.0=r351h0a44026_0
  - bioconductor-rsamtools=1.34.0=r351h0a44026_0
  - bioconductor-rtracklayer=1.42.1=r351h1de35cc_0
  - bioconductor-s4vectors=0.20.1=r351h470a237_0
  - bioconductor-shortread=1.40.0=r351h0a44026_0
  - bioconductor-summarizedexperiment=1.12.0=r351_0
  - bioconductor-systempiper=1.16.0=r351_0
  - bioconductor-tximport=1.10.0=r351_0
  - bioconductor-variantannotation=1.28.3=r351h1de35cc_0
  - bioconductor-xvector=0.22.0=r351h1de35cc_0
  - bioconductor-zlibbioc=1.28.0=r351h1de35cc_0
  - blas=1.0=mkl
  - bleach=1.4.2=py35_0
  - bwidget=1.9.11=1
  - bzip2=1.0.6=h1de35cc_5
  - c-compiler=1.0.1=h1de35cc_0
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.14.12=h9d4d9ac_1005
  - cctools=895=1
  - certifi=2018.8.24=py35_1001
  - cffi=1.11.5=py35h6174b99_1
  - clang=4.0.1=1
  - clang_osx-64=4.0.1=h1ce6c1d_11
  - clangxx=4.0.1=1
  - clangxx_osx-64=4.0.1=h22b1bf0_11
  - cmake=3.12.2=haff7e42_0
  - compiler-rt=4.0.1=hcfea43d_1
  - compilers=1.0.1=0
  - constantly=15.1.0=py35h28b3542_0
  - cryptography=2.3.1=py35hdbc3d79_0
  - curl=7.61.1=ha441bb4_0
  - cxx-compiler=1.0.1=h04f5b5a_0
  - cycler=0.10.0=py35hb89929e_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py35_1
  - entrypoints=0.2.3=py35_2
  - expat=2.2.6=h0a44026_0
  - fontconfig=2.13.1=h1027ab8_1000
  - fortran-compiler=1.0.1=h4f947d3_0
  - freetype=2.10.0=h24853df_0
  - fribidi=1.0.5=h1de35cc_0
  - gast=0.2.0=py35_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - gfortran_osx-64=4.8.5=h22b1bf0_8
  - glib=2.56.2=h67dad55_1001
  - graphite2=1.3.13=h2098e52_0
  - graphviz=2.40.1=hefbbd9a_2
  - grpcio=1.12.1=py35hd9629dc_0
  - gsl=2.4=h1de35cc_4
  - harfbuzz=1.9.0=h9889186_1001
  - html5lib=1.0.1=py35_0
  - hyperlink=18.0.0=py35_0
  - icu=58.2=h0a44026_1000
  - idna=2.7=py35_0
  - incremental=17.5.0=py35_0
  - intel-openmp=2019.3=199
  - ipykernel=4.10.0=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hf129286_0
  - ipywidgets=7.4.1=py35_0
  - java-jdk=8.0.92=1
  - jbig=2.1=h4d881f8_0
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=2.6.0=py35h2dd9e4b_0
  - jupyter=1.0.0=py35_7
  - jupyter_client=5.2.3=py35_0
  - jupyter_console=5.2.0=py35hd2aa692_1
  - jupyter_core=4.4.0=py35_0
  - kiwisolver=1.0.1=py35h219a9d8_0
  - krb5=1.16.1=h24a3359_6
  - ld64=274.2=1
  - libcurl=7.61.1=hf30b1f0_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=h01d97ff_1005
  - libopenblas=0.3.3=hdc02c5d_3
  - libpng=1.6.36=ha441bb4_0
  - libprotobuf=3.6.0=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.8.0=h322a93b_4
  - libtiff=4.0.10=h79f4b77_1001
  - libxcb=1.13=h1de35cc_1002
  - libxml2=2.9.8=hf14e9c8_1005
  - llvm=4.0.1=1
  - llvm-lto-tapi=4.0.1=1
  - llvm-meta=8.0.0=0
  - llvm-openmp=4.0.1=hcfea43d_1
  - llvmdev=8.0.0=h770b8ee_0
  - make=4.2.1=h3efe00b_1
  - markdown=2.6.11=py35_0
  - markupsafe=1.0=py35h1de35cc_1
  - mistune=0.8.3=py35h1de35cc_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35hb8a8100_0
  - mkl_random=1.0.1=py35h5d10147_1
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py35h41c2038_0
  - ncurses=6.1=h0a44026_1
  - notebook=5.6.0=py35_0
  - numpy=1.15.2=py35h6a91979_0
  - numpy-base=1.15.2=py35h8a80b8c_0
  - openssl=1.0.2r=h1de35cc_0
  - pandas=0.23.4=py35h6440ff4_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py35_1
  - pango=1.42.4=h060686c_0
  - parso=0.3.1=py35_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35h9517181_0
  - pip=10.0.1=py35_0
  - pixman=0.34.0=hca0a616_3
  - prometheus_client=0.3.1=py35h28b3542_0
  - prompt_toolkit=1.0.15=py35h93950c5_0
  - protobuf=3.6.0=py35h0a44026_0
  - pthread-stubs=0.4=h1de35cc_1001
  - ptyprocess=0.6.0=py35_0
  - pyasn1=0.4.5=py_0
  - pyasn1-modules=0.0.5=py35_0
  - pycparser=2.19=py35_0
  - pygments=2.2.0=py35h392a662_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.1=py35_0
  - pyqt=5.6.0=py35_2
  - python=3.5.6=hc167b69_0
  - python-dateutil=2.7.3=py35_0
  - pytz=2018.5=py35_0
  - pyzmq=17.1.2=py35h1de35cc_0
  - qt=5.6.2=h822fa55_1013
  - qtconsole=4.3.1=py35hd6d667b_0
  - r-abind=1.4_5=r351h6115d3f_1001
  - r-acepack=1.4.1=r351hfffe0aa_1002
  - r-amap=0.8_16=r351hbe7ee20_1000
  - r-assertthat=0.2.1=r351h6115d3f_0
  - r-backports=1.1.3=r351h46e59ec_1000
  - r-base=3.5.1=h539fb6c_1
  - r-base64enc=0.1_3=r351h46e59ec_1002
  - r-batchjobs=1.7=r351h6115d3f_1000
  - r-bbmisc=1.11=r351h46e59ec_1001
  - r-bh=1.69.0_1=r351h6115d3f_0
  - r-bindr=0.1.1=r351hf348343_0
  - r-bindrcpp=0.2.2=r351h32998d9_0
  - r-bit=1.1_14=r351h159158b_0
  - r-bit64=0.9_7=r351h46e59ec_1000
  - r-bitops=1.0_6=r351h46e59ec_1002
  - r-blob=1.1.1=r351_1001
  - r-boot=1.3_22=r351_0
  - r-brew=1.0_6=r351hf348343_4
  - r-car=3.0_3=r35h6115d3f_0
  - r-cardata=3.0_2=r351h6115d3f_0
  - r-catools=1.17.1.2=r351h466af19_0
  - r-cellranger=1.1.0=r351h6115d3f_1001
  - r-checkmate=1.9.1=r351h46e59ec_0
  - r-cli=1.1.0=r351h6115d3f_0
  - r-clipr=0.6.0=r351h6115d3f_0
  - r-cluster=2.0.7_1=r351h0b560c1_0
  - r-colorspace=1.4_1=r351h159158b_0
  - r-cowplot=0.9.4=r351h6115d3f_0
  - r-crayon=1.3.4=r351h6115d3f_1001
  - r-curl=3.3=r351h46e59ec_0
  - r-data.table=1.12.0=r351h46e59ec_0
  - r-dbi=1.0.0=r351h6115d3f_1001
  - r-dbplyr=1.2.2=r351hf348343_0
  - r-dendextend=1.12.0=r351h6115d3f_0
  - r-devtools=1.13.6=r351hf348343_0
  - r-dichromat=2.0_0=r351_2000
  - r-digest=0.6.18=r351h46e59ec_1000
  - r-dplyr=0.7.6=r351h32998d9_0
  - r-ellipse=0.4.1=r351h6115d3f_1001
  - r-ellipsis=0.1.0=r351h46e59ec_0
  - r-evaluate=0.13=r351h6115d3f_1
  - r-factoextra=1.0.5=r351_1001
  - r-factominer=1.41=r351h6115d3f_1001
  - r-fail=1.3=r351_1000
  - r-fansi=0.4.0=r351h46e59ec_1000
  - r-flashclust=1.01_2=r351hfffe0aa_1002
  - r-forcats=0.4.0=r351h6115d3f_0
  - r-foreign=0.8_71=r351h46e59ec_1002
  - r-formatr=1.6=r351h6115d3f_0
  - r-formula=1.2_3=r351h6115d3f_1001
  - r-futile.logger=1.4.3=r351h6115d3f_1001
  - r-futile.options=1.0.1=r351h6115d3f_1000
  - r-gdata=2.18.0=r351h6115d3f_1001
  - r-getopt=1.20.3=r351_0
  - r-ggfortify=0.4.7=r351h6115d3f_0
  - r-ggplot2=3.0.0=r351hf348343_0
  - r-ggpubr=0.2=r351h6115d3f_1000
  - r-ggrepel=0.8.0=r351h466af19_1002
  - r-ggsci=2.9=r351h6115d3f_1001
  - r-ggsignif=0.5.0=r351h6115d3f_0
  - r-git2r=0.23.0=r351h6402f54_0
  - r-glue=1.3.1=r351h159158b_0
  - r-gplots=3.0.1.1=r351h6115d3f_0
  - r-gridextra=2.3=r351h6115d3f_1001
  - r-gtable=0.3.0=r351h6115d3f_0
  - r-gtools=3.8.1=r351h46e59ec_1002
  - r-haven=2.1.0=r351h466af19_0
  - r-highr=0.8=r351h6115d3f_0
  - r-hmisc=4.1_1=r351hfffe0aa_1001
  - r-hms=0.4.2=r351h6115d3f_1000
  - r-htmltable=1.13.1=r351h6115d3f_1000
  - r-htmltools=0.3.6=r351h0a44026_1002
  - r-htmlwidgets=1.3=r351h6115d3f_1000
  - r-httpuv=1.4.5=r351h32998d9_0
  - r-httr=1.4.0=r351h6115d3f_1000
  - r-hwriter=1.3.2=r351h6115d3f_1001
  - r-irdisplay=0.5.0=r351hf348343_0
  - r-irkernel=0.8.12=r351_0
  - r-jsonlite=1.6=r351h46e59ec_1000
  - r-kernsmooth=2.23_15=r351hfffe0aa_1002
  - r-knitr=1.20=r351hf348343_0
  - r-labeling=0.3=r351h6115d3f_1001
  - r-lambda.r=1.2.3=r351h6115d3f_1000
  - r-later=0.7.3=r351h32998d9_0
  - r-lattice=0.20_38=r351h46e59ec_1000
  - r-latticeextra=0.6_28=r351h6115d3f_1001
  - r-lazyeval=0.2.2=r351h159158b_0
  - r-leaps=3.0=r351hfffe0aa_1002
  - r-lme4=1.1_21=r351hf99fc2c_0
  - r-locfit=1.5_9.1=r351h1de35cc_1002
  - r-magrittr=1.5=r351h6115d3f_1001
  - r-maptools=0.9_3=r351h46e59ec_1002
  - r-markdown=0.9=r351h46e59ec_1000
  - r-mass=7.3_51.3=r351h159158b_0
  - r-matrix=1.2_17=r351h159158b_0
  - r-matrixmodels=0.4_1=r351h6115d3f_1001
  - r-matrixstats=0.54.0=r351h46e59ec_1000
  - r-memoise=1.1.0=r351h6115d3f_1001
  - r-mgcv=1.8_28=r351h159158b_0
  - r-mime=0.6=r351h46e59ec_1000
  - r-minqa=1.2.4=r351hbe7ee20_1002
  - r-munsell=0.5.0=r351h6115d3f_1001
  - r-nbclust=3.0=r351h6115d3f_1000
  - r-nlme=3.1_137=r351hfffe0aa_1000
  - r-nloptr=1.2.1=r351h466af19_0
  - r-nnet=7.3_12=r351h46e59ec_1002
  - r-openssl=1.1=r351hd0de0e5_1001
  - r-openxlsx=4.1.0=r351h466af19_1000
  - r-pbdzmq=0.3_3=r351h32998d9_0
  - r-pbkrtest=0.4_7=r351h6115d3f_1001
  - r-pheatmap=1.0.12=r351h6115d3f_0
  - r-pillar=1.3.1=r351h6115d3f_1000
  - r-pkgconfig=2.0.2=r351h6115d3f_1001
  - r-plogr=0.2.0=r351h6115d3f_1001
  - r-plyr=1.8.4=r351h466af19_1002
  - r-polynom=1.3_9=r351h6115d3f_1001
  - r-prettyunits=1.0.2=r351h6115d3f_1001
  - r-progress=1.2.0=r351h6115d3f_1002
  - r-promises=1.0.1=r351h32998d9_0
  - r-ps=1.3.0=r351h46e59ec_1000
  - r-purrr=0.2.5=r351h6402f54_0
  - r-quantreg=5.40=r35haf69682_0
  - r-r6=2.4.0=r351h6115d3f_0
  - r-rcolorbrewer=1.1_2=r351h6115d3f_1001
  - r-rcpp=1.0.1=r351hf99fc2c_0
  - r-rcpparmadillo=0.9.300.2.0=r351hf99fc2c_0
  - r-rcppeigen=0.3.3.5.0=r351h466af19_0
  - r-rcurl=1.95_4.11=r351hc070d10_3
  - r-readr=1.3.1=r351h466af19_1000
  - r-readxl=1.3.1=r351hf99fc2c_0
  - r-rematch=1.0.1=r351h6115d3f_1001
  - r-repr=0.15.0=r351hf348343_0
  - r-reshape2=1.4.3=r351h32998d9_0
  - r-rio=0.5.16=r351h6115d3f_1000
  - r-rjson=0.2.20=r351h466af19_1000
  - r-rlang=0.3.3=r351h159158b_0
  - r-rocr=1.0_7=r351hf348343_4
  - r-rpart=4.1_13=r351h46e59ec_1002
  - r-rsqlite=2.1.1=r351h466af19_1000
  - r-rstudioapi=0.10=r351h6115d3f_0
  - r-scales=1.0.0=r351h466af19_1001
  - r-scatterplot3d=0.3_41=r351h6115d3f_1000
  - r-sendmailr=1.2_1=r351h6115d3f_1001
  - r-shiny=1.1.0=r351hf348343_0
  - r-snow=0.4_3=r351h6115d3f_1000
  - r-sourcetools=0.1.7=r351h32998d9_0
  - r-sp=1.3_1=r351h46e59ec_1000
  - r-sparsem=1.77=r351hfffe0aa_1001
  - r-stringi=1.4.3=r351hf99fc2c_0
  - r-stringr=1.4.0=r351h6115d3f_0
  - r-survival=2.44_1.1=r351h159158b_0
  - r-tibble=2.1.1=r351h159158b_0
  - r-tidyr=0.8.2=r351h466af19_1002
  - r-tidyselect=0.2.4=r351h32998d9_0
  - r-utf8=1.1.4=r351h46e59ec_1000
  - r-uuid=0.1_2=r351h6402f54_4
  - r-viridis=0.5.1=r351h6115d3f_1001
  - r-viridislite=0.3.0=r351h6115d3f_1001
  - r-whisker=0.3_2=r351hf348343_4
  - r-withr=2.1.2=r351h6115d3f_1000
  - r-xfun=0.6=r351h6115d3f_0
  - r-xml=3.98_1.16=r351h46e59ec_1000
  - r-xtable=1.8_3=r351_2000
  - r-yaml=2.2.0=r351h46e59ec_1001
  - r-zip=2.0.1=r351h159158b_0
  - readline=7.0=h1de35cc_5
  - rhash=1.3.6=hdbc3d79_0
  - rpy2=2.9.1=py35r351h1d22016_0
  - scipy=1.1.0=py35h28f7352_1
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35h28b3542_0
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35h0a44026_0
  - six=1.11.0=py35_1
  - sqlite=3.27.2=ha441bb4_0
  - tensorboard=1.10.0=py35hdc36e2c_0
  - tensorflow=1.10.0=eigen_py35h5ac2770_0
  - tensorflow-base=1.10.0=eigen_py35h4f0eeca_0
  - termcolor=1.1.0=py35_1
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35hf8009f4_0
  - tk=8.6.8=ha441bb4_0
  - tktable=2.10=h1de35cc_0
  - tornado=5.1.1=py35h1de35cc_0
  - traitlets=4.3.2=py35hd3d1486_0
  - twisted=17.5.0=py35_0
  - wcwidth=0.1.7=py35hdd0c235_0
  - webencodings=0.5.1=py35_1
  - werkzeug=0.14.1=py35_0
  - wget=1.19.5=hf30b1f0_0
  - wheel=0.31.1=py35_0
  - widgetsnbextension=3.4.1=py35_0
  - xorg-kbproto=1.0.7=h1de35cc_1002
  - xorg-libx11=1.6.7=h1de35cc_1000
  - xorg-libxau=1.0.9=h1de35cc_0
  - xorg-libxdmcp=1.1.3=h01d97ff_0
  - xorg-libxrender=0.9.10=h01d97ff_1002
  - xorg-renderproto=0.11.1=h1de35cc_1002
  - xorg-xproto=7.0.31=h1de35cc_1007
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=h1de35cc_3
  - zope=1.0=py35_1
  - zope.interface=4.5.0=py35h1de35cc_0
  - zstd=1.3.7=h5bba6e5_0
prefix: /Users/dhelekal/anaconda3/envs/py35v3

